### PR TITLE
steam-deck support

### PR DESCRIPTION
**Pull request by aeon0**

### CODE REVIEW

**Comment by ThaMighty90** [comment]
Hey if you need any help testing this I can help you I just setup D4 on my steam deck. Just let me know what I have to do.

**Comment by chrisoro** [comment]
A bit of cleanup, will close this

**Comment by Rick45** [comment]
Are you going to implement this pt is on hold for now?

**Comment by chrisoro** [comment]
This is on hold since January, sorry :(

**Pull request closed without merging**
